### ISSUE TITLE
skip some or most magic commands

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/jupyter-retired#12]
remove a few minor things like %capture, %pastebin which aren't that important.
shorten %debug demo a little

**Comment by wikfeldt** [comment]
we can consider having a separate notebook (which can be mentioned but not taught explicitly) with many magic commands and some example usage

**Comment by wikfeldt** [comment]
perhaps best to only discuss the magics explicitly using `%quickref`, and then just use a few magics in exercises

**Comment by bast** [comment]
I like the suggestion.
