### ISSUE TITLE
Suggestion for reordering sections and "git diff" exercise

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter-retired#16]
IMO the time spent to explain the "git diff" exercise is disproportionate to the benefit. On the other hand last time we ran out of time with the nice interact examples which I think should come first. IMO the "git diff" part can be left out if time is short since I find it more important that people see the power of notebooks rather that everybody understands the pitfalls of JSON diffing.

**Comment by wikfeldt** [comment]
there's no longer an exercise on `git diff`, only a section describing the challenges in using git with notebooks, and a possible solution through nbdime. It's only mentioned and not dwelled on for long.
 So let's resolve this issue
